
kuka_kr6:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  group1_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - joint_a1
      - joint_a2
      - joint_a3
      - joint_a4
      - joint_a5
      - joint_a6
    gains:
      joint_a1: {p: 100, d: 0.1, i: 1}
      joint_a2: {p: 100, d: 0.1, i: 1}
      joint_a3: {p: 100, d: 0.1, i: 1}
      joint_a4: {p: 100, d: 0.1, i: 1}
      joint_a5: {p: 100, d: 0.1, i: 1}
      joint_a6: {p: 100, d: 0.1, i: 1}