
kuka_kr6:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  group1_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - joint_a1
      - joint_a2
      - joint_a3
      - joint_a4
      - joint_a5
      - joint_a6